<a href="https://colab.research.google.com/github/Rabia17/Facial-recognition/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [4]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)


[1 2 3 4 5]


In [28]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
a.shape

(10,)

In [31]:
a.shape = (10,1)
a
 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [32]:
z=np.ones(10)
type(z[0])

numpy.float64

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) #2-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #3-D array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])  #acess 6  

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

#slicing 
#slicing index 1 to 5 
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

#4 index to end 
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

#Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

# 5 and 6  -3=4 , -1=7
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

#7 8 9
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

#From both retun index 2 
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

#datatypes 
arr = np.array([1, 2, 3, 4], dtype='i4') #define data type 
print(arr)

# Change data type from float to integer 
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

#copy 1,2,3,4,5 
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42 #replace

